"""add_status_and_file_metadata_to_files

Revision ID: b5cb11daced4
Revises: 7138935788ee
Create Date: 2025-09-14 09:22:28.309425+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b5cb11daced4"
down_revision: Union[str, None] = "7138935788ee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "upd_files",
        sa.Column(
            "status",
            sa.String(length=20),
            server_default="pending",
            nullable=False,
            comment="Upload status: pending, uploading, available, deleted",
        ),
    )
    op.add_column(
        "upd_files",
        sa.Column(
            "file_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Additional file metadata (e.g., dimensions for images, duration for videos)",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("upd_files", "file_metadata")
    op.drop_column("upd_files", "status")
    # ### end Alembic commands ###
