"""Add storage tables for files buckets and processing jobs

Revision ID: 7138935788ee
Revises: 3430554160eb
Create Date: 2025-09-01 02:40:35.856607+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7138935788ee"
down_revision: Union[str, None] = "3430554160eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "upd_bucket",
        sa.Column(
            "name",
            sa.String(length=255),
            nullable=False,
            comment="Actual bucket name (e.g., 'investment-reports-dev')",
        ),
        sa.Column(
            "slug",
            sa.String(length=255),
            nullable=False,
            comment="Human-readable slug for URLs (e.g., 'investment-reports')",
        ),
        sa.Column(
            "provider",
            sa.String(length=50),
            nullable=False,
            comment="Cloud provider: 'gcp', 'aws', 'azure'",
        ),
        sa.Column(
            "is_public",
            sa.Boolean(),
            nullable=False,
            comment="Whether bucket contents are publicly accessible",
        ),
        sa.Column(
            "created_by_id",
            sa.UUID(),
            nullable=False,
            comment="User who created this bucket",
        ),
        sa.Column(
            "updated_by_id",
            sa.UUID(),
            nullable=True,
            comment="User who last updated this bucket",
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_upd_bucket_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
            name=op.f("fk_upd_bucket_updated_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_upd_bucket")),
    )
    op.create_index(op.f("ix_upd_bucket_slug"), "upd_bucket", ["slug"], unique=True)
    op.create_table(
        "upd_files",
        sa.Column(
            "bucket_id",
            sa.UUID(),
            nullable=False,
            comment="Reference to the bucket containing this file",
        ),
        sa.Column(
            "filename",
            sa.String(length=255),
            nullable=False,
            comment="Display name for the file (can be renamed)",
        ),
        sa.Column(
            "original_filename",
            sa.String(length=255),
            nullable=False,
            comment="Original filename when uploaded",
        ),
        sa.Column(
            "extension",
            sa.String(length=10),
            nullable=True,
            comment="File extension (e.g., '.pdf', '.xlsx')",
        ),
        sa.Column(
            "file_size", sa.BigInteger(), nullable=True, comment="File size in bytes"
        ),
        sa.Column(
            "content_type",
            sa.String(length=100),
            nullable=True,
            comment="MIME type (e.g., 'application/pdf')",
        ),
        sa.Column(
            "storage_path",
            sa.String(length=500),
            nullable=False,
            comment="Full path within the bucket (e.g., 'reports/2024/Q1/report.pdf')",
        ),
        sa.Column(
            "created_by_id",
            sa.UUID(),
            nullable=False,
            comment="User who uploaded this file",
        ),
        sa.Column(
            "updated_by_id",
            sa.UUID(),
            nullable=True,
            comment="User who last updated this file metadata",
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bucket_id"],
            ["upd_bucket.id"],
            name=op.f("fk_upd_files_bucket_id_upd_bucket"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_upd_files_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
            name=op.f("fk_upd_files_updated_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_upd_files")),
        sa.UniqueConstraint("bucket_id", "storage_path", name="uq_bucket_storage_path"),
    )
    op.create_index(
        op.f("ix_upd_files_bucket_id"), "upd_files", ["bucket_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_upd_files_bucket_id"), table_name="upd_files")
    op.drop_table("upd_files")
    op.drop_index(op.f("ix_upd_bucket_slug"), table_name="upd_bucket")
    op.drop_table("upd_bucket")
    # ### end Alembic commands ###
