"""create users table

Revision ID: 3430554160eb
Revises:
Create Date: 2025-08-25 06:54:30.772724+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3430554160eb"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "clerk_user_id",
            sa.String(length=255),
            nullable=False,
            comment="Unique identifier from Clerk authentication system",
        ),
        sa.Column(
            "preferred_name",
            sa.String(length=255),
            nullable=True,
            comment="User's preferred display name for UI",
        ),
        sa.Column(
            "initials",
            sa.String(length=2),
            nullable=True,
            comment="User initials for UI display (max 2 characters)",
        ),
        sa.Column(
            "role",
            sa.String(length=50),
            nullable=True,
            comment="User role for access control (e.g., user, admin)",
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(
        op.f("ix_users_clerk_user_id"), "users", ["clerk_user_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_clerk_user_id"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
